
import { RemoteButton } from "../../custom-components.slint";
import { RemoteScreenID } from "../../remote-screens-index.slint";
import { Theme } from "../../globals.slint";

export component HDRDVDInfoScreen {
    VerticalLayout {
        VerticalLayout {
            spacing: 30px;
            alignment: center;

            Text {
                text: "Open disc tray with \"OPEN/CLOSE\" button on top right of HDR box. Insert disc and close tray, then press \"Done\" on remote.";
                wrap: word-wrap;
                font-size: 24px;
                color: Theme.default_general_text_colour;
            }

            RemoteButton {
                height: 80px;
                screen_id: RemoteScreenID.HDR-DVD;
                bg_colour: lime;
                text: "Done";
            }
        }
        
        VerticalLayout {
            alignment: end;

            RemoteButton {
                height: 40px;
                screen_id: RemoteScreenID.HDR_HOME;
                text: "Back";
            }
        }
    }
}