
import { HDRChannelGrid, HDRRemoteNavPanel, RemoteButton } from "../../custom-components.slint";
import { RemoteScreenID } from "../../remote-screens-index.slint";
import { Symbols, Theme } from "../../globals.slint";

export component HDRRecordScreen {
    VerticalLayout {
        spacing: 20px;

        HDRChannelGrid {}

        GridLayout {
            height: 90px;
            spacing: 10px;

            HorizontalLayout {
                spacing: 10px;

                RemoteButton {
                    action_list_id: "HDR_RED";
                    bg_colour: red;
                }

                RemoteButton {
                    action_list_id: "HDR_GREEN";
                    bg_colour: green;
                }
            }

            RemoteButton {
                row: 0;
                col: 1;
                icon: Symbols.bin;
                action_list_id: "HDR_DELETE";
            }

            RemoteButton {
                row: 0;
                col: 2;
                text: "RECORD";
                bg_colour: Theme.record_bg_colour;
                text_colour: Theme.record_fg_colour;
                action_list_id: "HDR_RECORD";
            }
            
            RemoteButton {
                row: 0;
                col: 3;
                text: "GUIDE";
                action_list_id: "HDR_GUIDE";
                bg_colour: Theme.info_bg_colour;
                text_colour: Theme.info_fg_colour;
            }

            RemoteButton {
                row: 1;
                col: 0;
                text: "PLAY PAGE";
                screen_id: RemoteScreenID.HDR_PLAY;
            }

            RemoteButton {
                row: 1;
                col: 1;
                text: "CHECK";
                action_list_id: "HDR_PROG_CHECK";
            }

            RemoteButton {
                row: 1;
                col: 2;
                colspan: 2;
                text: "HDR OFF";
                action_list_id: "SHUTDOWN_HDR";
                screen_id: RemoteScreenID.TV_CHANNELS;
                bg_colour: Theme.power_bg_colour;
                text_colour: Theme.power_fg_colour;
            }
        }
        
        VerticalLayout {
            alignment: end;
            HDRRemoteNavPanel {}
        }
    }
}