
import { HDRDVDPlaybackControlPanel, HDRRemoteNavPanel, RemoteButton } from "../../custom-components.slint";
import { RemoteScreenID } from "../../remote-screens-index.slint";
import { Theme } from "../../globals.slint";

export component HDRDVDScreen {
    VerticalLayout {
        spacing: 10px;

        VerticalLayout {
            alignment: center;
            HDRDVDPlaybackControlPanel {
                height: 70%;
            }
        }

        RemoteButton {
            height: 40px;
            action_list_id: "SHUTDOWN_HDR";
            screen_id: RemoteScreenID.TV_CHANNELS;
            text: "HDR OFF";
            bg_colour: Theme.power_bg_colour;
            text_colour: Theme.power_fg_colour;
        }

        HDRRemoteNavPanel {}
    }
}