
import { HDRChannelGrid, HDRRemoteNavPanel, RemoteButton, HDRRecordingPlaybackControlPanel } from "../../custom-components.slint";
import { RemoteScreenID } from "../../remote-screens-index.slint";
import { Symbols, Theme } from "../../globals.slint";

export component HDRPlayScreen {
    RemoteButton {
        x: 0;
        y: 400px;
        width: 80px;
        height: 80px;
        action_list_id: "HDR_DELETE";
        icon: Symbols.bin;
    }

    VerticalLayout {
        spacing: 20px;

        VerticalLayout {
            alignment: center;
            vertical-stretch: 1;

            HDRRecordingPlaybackControlPanel{
                height: 70%;
            }
        }
        
        HorizontalLayout {
            spacing: 10px;
        
            RemoteButton {
                height: 40px;
                text: "RECORD PAGE";
                screen_id: RemoteScreenID.HDR_RECORD;
            }

            RemoteButton {
                text: "HDR OFF";
                action_list_id: "SHUTDOWN_HDR";
                screen_id: RemoteScreenID.TV_CHANNELS;
                bg_colour: Theme.power_bg_colour;
                text_colour: Theme.power_fg_colour;
            }
        }
        
        VerticalLayout {
            alignment: end;
            HDRRemoteNavPanel {}
        }
    }
}