
import { Button } from "std-widgets.slint";

import { ScreenTemplate, MultiPageRemoteButtonGrid } from "../custom-components.slint";
import { TVChannelButtonData } from "../custom-component-data.slint";
import { Symbols } from "../globals.slint";

export component ChannelScreen { //whole screen for tv channel selection    
    ScreenTemplate {
        channelGrid := MultiPageRemoteButtonGrid { //display the grid of channels
            num_cols: 4;
            num_rows: 5;
            button_width : 80px;
            button_height : 60px;
            grid_data: TVChannelButtonData.data;
        }
    }
}