
import { RemoteButton } from "../custom-components.slint";
import { RemoteScreenID } from "../remote-screens-index.slint";
import { Theme, Symbols } from "../globals.slint";

export component HomeScreen {
    property <length> btn_height: 80px;
    
    VerticalLayout {
        height: 50%;
        alignment: space-around;

        RemoteButton {
            height: btn_height;
            action_list_id: "STARTUP_AMAZON";
            screen_id: RemoteScreenID.AMAZON;
            icon: Symbols.amazon;
            bg_colour: Theme.amazon_dark_blue;
            font_size: Theme.larger_font_size;
        }

        RemoteButton {
            height: btn_height;
            text: "TV";
            action_list_id: "STARTUP_TV";
            screen_id: RemoteScreenID.TV_CHANNELS;
            bg_colour: lime;
            font_size: Theme.larger_font_size;
        }

        RemoteButton {
            height: btn_height;
            text: "Radio";
            action_list_id: "STARTUP_RADIO";
            screen_id: RemoteScreenID.SPEAKERS_RADIO;
            font_size: Theme.larger_font_size;
        }

        RemoteButton {
            height: btn_height;
            text: "Speaker Bluetooth";
            action_list_id: "STARTUP_BLUETOOTH";
            screen_id: RemoteScreenID.SPEAKERS_BLUETOOTH;
            bg_colour: blue;
            text_colour: white;
            font_size: Theme.larger_font_size;
        }
    }

    VerticalLayout {
        alignment: end;
        width: 50%;
        x: 0;

        HorizontalLayout {
            height: 80px;
            spacing: 10px;

            RemoteButton {
                text: "SPKR POWER";
                action_list_id: "SPEAKERS_POWER";
                bg_colour: Theme.power_bg_colour;
                text_colour: Theme.power_fg_colour;
                font_size: Theme.larger_font_size;
            }
    
            RemoteButton {
                text: "TV POWER";
                action_list_id: "TV_POWER";
                bg_colour: Theme.power_bg_colour;
                text_colour: Theme.power_fg_colour;
                font_size: Theme.larger_font_size;
            }
        }
    }
}