
import { RemoteButton } from "../custom-components.slint";
import { Logic, Symbols } from "../globals.slint";
import { RemoteScreenID } from "../remote-screens-index.slint";
import { Button } from "std-widgets.slint";

export component IRReceiveScreen {
    init => {
        Logic.disable_sleep();
    }

    VerticalLayout {
        VerticalLayout {
            alignment: start;
            spacing: 10px;

            Text {
                font-size: 20px;
                color: white;
                text: "Learn Mode";
            }
    
            Text {
                font-size: 16px;
                text: "Connect usb to pc and begin monitoring\nPress button below to begin listening for signal, the remote will be stuck listening until a signal is received (or it is powered off)\nPoint remote at receiver and press a button\nThe code will be printed out in the monitor terminal\nThe hex code should be used for creating ACTIONs in remotes.h";
                color: white;
                wrap: word-wrap;
            }
    
            Button {
                height: 60px;
                text: "Click to begin receiving";
    
                clicked => {
                    Logic.begin_ir_receive();
                }
            }
        }

        RemoteButton {
            height: 40px;
            icon: Symbols.home;
            screenID: RemoteScreenID.HOME;

            pointer-event(event) => {
                if (event.kind == PointerEventKind.up && self.held == true) {
                    Logic.enable_sleep();
                }
            }
        }
    }
}