
import { RemoteButton } from "../custom-components.slint";
import { Logic, Symbols } from "../globals.slint";
import { RemoteScreenID } from "../remote-screens-index.slint";
import { Button } from "std-widgets.slint";

export component IRReceiveScreen {
    init => {
        Logic.disable_sleep(); //when on this screen, disable sleep as device may not be touched for a few seconds while learning codes
        Logic.disable_auto_brightness(); //disable auto brightness to prevent warnings about ledc fade too slow
    }

    VerticalLayout {
        VerticalLayout {
            alignment: start;
            spacing: 10px;

            Text {
                font-size: 20px;
                color: white;
                text: "Learn Mode";
            }
    
            Text {
                font-size: 16px;
                text: "Connect usb to pc and begin monitoring\nPress button below to begin listening for signal, the remote will be stuck listening until a signal is received (or remote powered off)\nPoint remote at receiver and press a button\nThe code will be printed out in the monitor terminal\nThe code should be used for creating ACTIONs in remotes.h";
                color: white;
                wrap: word-wrap;
            }
    
            Button {
                height: 100px;
                text: "Click to begin receiving";
    
                clicked => {
                    Logic.begin_ir_receive();
                }
            }
        }

        RemoteButton {
            height: 40px;
            icon: Symbols.home;
            screen_id: RemoteScreenID.SCREEN_LIST;

            press_release => {
                Logic.enable_sleep();
                Logic.enable_auto_brightness();
            }
        }
    }
}