
import { RemoteButton } from "../custom-components.slint";
import { Logic, Symbols } from "../globals.slint";
import { RemoteScreenID } from "../remote-screens-index.slint";
import { Button } from "std-widgets.slint";

export component IRReceiveScreen {
    VerticalLayout {
        alignment: start;
        spacing: 10px;

        Text {
            font-size: 24px;
            color: white;
            text: "Learn Mode";
        }

        Text {
            font-size: 18px;
            text: "Connect usb to pc and begin monitoring\nPress button below to begin listening for signal, the remote will be stuck listening until a signal is received (or remote powered off)\nPoint original remote at front of this one and press a button\nThe code will be printed out in the monitor terminal\nThe code should be used for creating ACTIONs in remotes.h";
            color: white;
            wrap: word-wrap;
        }

        RemoteButton {
            height: 100px;
            text: "Click to begin receiving";

            press_release => {
                Logic.begin_ir_receive();
            }
        }
    }
}