
import { RemoteButton } from "../custom-components.slint";
import { RemoteScreenID } from "../remote-screens-index.slint";

export component ScreenListScreen {
    VerticalLayout { //container for whole screen
        spacing: 10px;
        alignment: stretch;

        RemoteButton {
            text: "Home";
            screen_id: RemoteScreenID.HOME;
        }

        RemoteButton {
            text: "TV All Buttons";
            screen_id: RemoteScreenID.TV_ALL_BUTTONS;
        }

        RemoteButton {
            text: "TV Channels";
            screen_id: RemoteScreenID.TV_CHANNELS;
        }

        RemoteButton {
            text: "TV Apps";
            screen_id: RemoteScreenID.TV_APPS;
        }

        RemoteButton {
            text: "NAS/Photo/Video";
            screen_id: RemoteScreenID.NAS_PHOTO_VIDEO;
        }

        RemoteButton {
            text: "Speakers All Buttons";
            screen_id: RemoteScreenID.SPEAKERS_ALL_BUTTONS;
        }

        RemoteButton {
            text: "HDR All Buttons";
            screen_id: RemoteScreenID.HDR_ALL_BUTTONS;
        }

        RemoteButton {
            text: "YouView All Buttons";
            screen_id: RemoteScreenID.YOUVIEW_ALL_BUTTONS;
        }

        RemoteButton {
            text: "IR Code Learning";
            screen_id: RemoteScreenID.IR_RECEIVE;
        }

        // Button {
        //     text: "sleep test";
        //     clicked => {
        //         Logic.sleep();
        //     }
        // }
    }
}