
import { Button } from "std-widgets.slint";

import { MultiPageRemoteButtonGrid, TVRemoteNavPanel, RemoteButton } from "../../custom-components.slint";
import { TVChannelButtonData } from "../../custom-component-data.slint";
import { Symbols } from "../../globals.slint";
import { RemoteScreenID } from "../../remote-screens-index.slint";


export component TVChannelScreen { //whole screen for tv channel selection
    VerticalLayout {
        spacing: 20px;

        MultiPageRemoteButtonGrid { //display the grid of channels
            num_cols: 5;
            num_rows: 5;
            button_width : 80px;
            button_height : 70px;
            grid_data: TVChannelButtonData.data;
        }

        GridLayout {
            spacing: 10px;
            height: 80px;
            
            Row {
                RemoteButton {
                    bg_colour: red;
                    action_list_id: "TV_RED";
                }
                
                RemoteButton {
                    bg_colour: green;
                    action_list_id: "TV_GREEN";
                }

                RemoteButton {
                    text: "Guide";
                    action_list_id: "TV_GUIDE";
                }
    
                RemoteButton {
                    text: "TV Apps";
                    screen_id: RemoteScreenID.TV_APPS;
                }
            }
            
            Row {
                RemoteButton {
                    text: "NAS";
                    screen_id: RemoteScreenID.NAS_PHOTO_VIDEO;
                }
    
                RemoteButton {
                    text: "TV off";
                    action_list_id: "SHUTDOWN_TV";
                    screen_id: RemoteScreenID.HOME;
                }
    
                RemoteButton {
                    text: "HDR on";
                }
    
                RemoteButton {
                    text: "YouView on";
                }
            }
            
        }

        VerticalLayout {
            alignment: end;
            TVRemoteNavPanel {}
        }
    }
}