
import { Button } from "std-widgets.slint";

import { TVRemoteNavPanel, RemoteButton, TVChannelGrid } from "../../custom-components.slint";
import { TVChannelButtonData } from "../../custom-component-data.slint";
import { Symbols } from "../../globals.slint";
import { RemoteScreenID } from "../../remote-screens-index.slint";


export component TVChannelScreen { //whole screen for tv channel selection
    VerticalLayout {
        spacing: 20px;

        TVChannelGrid {}

        VerticalLayout {
            spacing: 10px;
            height: 90px;
            
            HorizontalLayout {
                spacing: 10px;

                RemoteButton {
                    bg_colour: red;
                    action_list_id: "TV_RED";
                    horizontal-stretch: 0.45;
                }
                
                RemoteButton {
                    bg_colour: green;
                    action_list_id: "TV_GREEN";
                    horizontal-stretch: 0.45;
                }

                RemoteButton {
                    text: "NAS";
                    screen_id: RemoteScreenID.TV_PLAYBACK;
                    horizontal-stretch: 1;
                }

                RemoteButton {
                    text: "Guide";
                    horizontal-stretch: 1;
                    action_list_id: "TV_GUIDE";
                }
    
                RemoteButton {
                    text: "TV Apps";
                    horizontal-stretch: 1;
                    screen_id: RemoteScreenID.TV_APPS;
                }
            }
            
            HorizontalLayout {
                spacing: 10px;

                RemoteButton {
                    text: "Pause TV";
                    action_list_id: "TV_PAUSE";
                    screen_id: RemoteScreenID.TV_PLAYBACK;
                }
    
                RemoteButton {
                    text: "TV off";
                    action_list_id: "SHUTDOWN_TV";
                    screen_id: RemoteScreenID.HOME;
                }
    
                RemoteButton {
                    text: "HDR on";
                    action_list_id: "STARTUP_HDR";
                    screen_id: RemoteScreenID.HDR_HOME;
                }
    
                RemoteButton {
                    text: "YouView on";
                }
            }
            
        }

        VerticalLayout {
            alignment: end;
            TVRemoteNavPanel {}
        }
    }
}