
import { Button } from "std-widgets.slint";

import { TVRemoteNavPanel, RemoteButton, TVChannelGrid } from "../../custom-components.slint";
import { ChannelButtonData } from "../../custom-component-data.slint";
import { Symbols, Theme } from "../../globals.slint";
import { RemoteScreenID } from "../../remote-screens-index.slint";


export component TVChannelScreen { //whole screen for tv channel selection
    VerticalLayout {
        spacing: 20px;

        TVChannelGrid {}

        VerticalLayout {
            spacing: 10px;
            height: 90px;
            
            HorizontalLayout {
                spacing: 10px;

                RemoteButton {
                    bg_colour: red;
                    action_list_id: "TV_RED";
                    horizontal-stretch: 0.45;
                }
                
                RemoteButton {
                    bg_colour: green;
                    action_list_id: "TV_GREEN";
                    horizontal-stretch: 0.45;
                }

                RemoteButton {
                    text: "NAS";
                    screen_id: RemoteScreenID.TV_PLAYBACK;
                    horizontal-stretch: 1;
                    action_list_id: "STARTUP_NAS";
                }

                RemoteButton {
                    text: "GUIDE";
                    horizontal-stretch: 1;
                    action_list_id: "TV_GUIDE_DISMISS_MESSAGE";
                }
    
                RemoteButton {
                    text: "TV APPS";
                    horizontal-stretch: 1;
                    screen_id: RemoteScreenID.TV_APPS;
                }
            }
            
            HorizontalLayout {
                spacing: 10px;

                RemoteButton {
                    text: "PAUSE TV";
                    action_list_id: "TV_PAUSE";
                    screen_id: RemoteScreenID.TV_PLAYBACK;
                    bg_colour: Theme.playback_bg_colour_3;
                    text_colour: Theme.playback_fg_colour_3;
                }
    
                RemoteButton {
                    text: "TV OFF";
                    action_list_id: "SHUTDOWN_TV";
                    screen_id: RemoteScreenID.HOME;
                    bg_colour: Theme.power_bg_colour;
                    text_colour: Theme.power_fg_colour;
                }
    
                RemoteButton {
                    text: "HDR/DVD";
                    action_list_id: "STARTUP_HDR";
                    screen_id: RemoteScreenID.HDR_HOME;
                    bg_colour: Theme.power_bg_colour;
                    text_colour: Theme.power_fg_colour;
                }
    
                RemoteButton {
                    text: "YVIEW";
                    action_list_id: "STARTUP_YOUVIEW";
                    screen_id: RemoteScreenID.YOUVIEW_HOME;
                    bg_colour: Theme.power_bg_colour;
                    text_colour: Theme.power_fg_colour;
                }
            }
            
        }

        VerticalLayout {
            alignment: end;
            TVRemoteNavPanel {}
        }
    }
}