
import { YouViewRemoteNavPanel, RemoteButton, YouViewPlaybackControlPanel } from "../../custom-components.slint";
import { RemoteScreenID } from "../../remote-screens-index.slint";
import { Symbols, Theme } from "../../globals.slint";

export component YouViewPlayScreen {
    RemoteButton {
        x: 0;
        y: 400px;
        width: 80px;
        height: 80px;
        action_list_id: "YOUVIEW_DELETE_SUB";
        icon: Symbols.bin;
    }

    VerticalLayout {
        spacing: 20px;

        VerticalLayout {
            alignment: center;
            vertical-stretch: 1;

            YouViewPlaybackControlPanel{
                height: 70%;

                RemoteButton {
                    row: 0;
                    col: 1;
                    action_list_id: "YOUVIEW_HOME";
                    text: "YOUVIEW";
                    bg_colour: blue;
                    text_colour: white;
                }
            }
        }
        
        HorizontalLayout {
            spacing: 10px;
        
            RemoteButton {
                height: 40px;
                text: "RECORD PAGE";
                screen_id: RemoteScreenID.YOUVIEW_RECORD;
            }

            RemoteButton {
                text: "YouView OFF";
                action_list_id: "SHUTDOWN_YOUVIEW";
                screen_id: RemoteScreenID.TV_CHANNELS;
                bg_colour: Theme.power_bg_colour;
                text_colour: Theme.power_fg_colour;
            }
        }
        
        VerticalLayout {
            alignment: end;
            YouViewRemoteNavPanel {}
        }
    }
}