
//general icon symbols which may want to be used on various screens

export global Symbols {
    out property <image> arrow-left:    @image-url("icons/buttons/arrow-left.png");
    out property <image> arrow-right:   @image-url("icons/buttons/arrow-right.png");
    out property <image> arrow-up:      @image-url("icons/buttons/arrow-up.png");
    out property <image> arrow-down:    @image-url("icons/buttons/arrow-down.png");
    out property <image> home:          @image-url("icons/buttons/home.png");
}